apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yannb
  name: yannb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yannb
  template:
    metadata:
      labels:
        app: yannb
    spec:
      containers:
      - image: replace
        name: yannb-container
        ports:
        - containerPort: 80  
        volumeMounts:
        - mountPath: /tmp
          name: vol
      volumes:
      - name: vol
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yannb
  name: yannb-svc
spec:
  type: NodePort
  selector:
    app: yannb
  ports:
  - port: 8888          
    targetPort: 80      
    protocol: TCP
