apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopsachraf
  name: devopsachraf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsachraf
  strategy: {}
  template:
    metadata:
      labels:
        app: devopsachraf
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: replace
        name: devopsachraf-container
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopsachraf
  name: devopsachraf-svc
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: devopsachraf
  type: NodePort